# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftAgent < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftaBot/driftabot-engine"
  version "5.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftaBot/engine/releases/download/v5.3.1/drift-agent_darwin_amd64.tar.gz"
      sha256 "5aa4b5b329197fef161ff123c961a171d577681efb1d9d28079730ab56f65076"

      define_method(:install) do
        bin.install "drift-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftaBot/engine/releases/download/v5.3.1/drift-agent_darwin_arm64.tar.gz"
      sha256 "296532d54e4df09149b489c73d738497276379b95d0678b37104153814b05ca8"

      define_method(:install) do
        bin.install "drift-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftaBot/engine/releases/download/v5.3.1/drift-agent_linux_amd64.tar.gz"
      sha256 "60592818996bff9e81a64764161a5fc81709c6239a18cd16f58fd6eafa0b564b"
      define_method(:install) do
        bin.install "drift-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftaBot/engine/releases/download/v5.3.1/drift-agent_linux_arm64.tar.gz"
      sha256 "8f3e14017f0d4e9740700a2b5878c5b82a8caa98ebf0b8a8a18c2ff59386fe37"
      define_method(:install) do
        bin.install "drift-agent"
      end
    end
  end

  test do
    system "#{bin}/drift-agent", "--help"
  end
end
