# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Driftabot < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftaBot/cli"
  version "6.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftaBot/engine/releases/download/v6.0.2/driftabot_darwin_amd64.tar.gz"
      sha256 "b999e797e74e73892589173a1ccfaf23afd8540b02ec3ec52450cb0d3bfe9cba"

      define_method(:install) do
        bin.install "driftabot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftaBot/engine/releases/download/v6.0.2/driftabot_darwin_arm64.tar.gz"
      sha256 "90e640183c706a4a411a63a0e0567d5754652bf30350213b69241014014bd526"

      define_method(:install) do
        bin.install "driftabot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftaBot/engine/releases/download/v6.0.2/driftabot_linux_amd64.tar.gz"
      sha256 "c6a690249ab3dffa88b568fa4ae03b8513ec7880fa12877c3d4370eb36fced43"
      define_method(:install) do
        bin.install "driftabot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftaBot/engine/releases/download/v6.0.2/driftabot_linux_arm64.tar.gz"
      sha256 "196a7efc6122f4c2ed570ea7e9adf0a1a9a20f2d78d77d44e522128d05f1073f"
      define_method(:install) do
        bin.install "driftabot"
      end
    end
  end

  test do
    system "#{bin}/driftabot", "--help"
  end
end
