# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftGuard < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftAgent/api-drift-engine"
  version "5.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_darwin_amd64.tar.gz"
      sha256 "e9da6e32328fbf02f522ecc8dbe7da61e6c11472e6d6d01cc25736d98623bf8a"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_darwin_arm64.tar.gz"
      sha256 "c1e99b7b1f59ac6ad15ebd3048a0c3b496e99d7824d22a658edb8989a8f61df2"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_linux_amd64.tar.gz"
      sha256 "092a2114ead1216199d01453def3acb3e3dd1dbe521382ce791615805f7a32be"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_linux_arm64.tar.gz"
      sha256 "31b7dfcac450243b63fe940887fe9244e8bf6042d2eaf6c01f1e1b66941dfd2e"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  test do
    system "#{bin}/drift-guard", "--help"
  end
end
