# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftAgent < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftAgent/api-drift-engine"
  version "5.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.3.0/drift-agent_darwin_amd64.tar.gz"
      sha256 "083814d7be0ce48e4150469302947afef808ae7846b7caca325763f38d4ab894"

      define_method(:install) do
        bin.install "drift-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.3.0/drift-agent_darwin_arm64.tar.gz"
      sha256 "b36eab30f883ba459a78264d67d720eb0c02294fb176c5aa0144b61d71a3f847"

      define_method(:install) do
        bin.install "drift-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.3.0/drift-agent_linux_amd64.tar.gz"
      sha256 "64e19eb0f2b2a0d18eaf25a5db8598f659dc34ff1e507a2db96ffc95e970fa71"
      define_method(:install) do
        bin.install "drift-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.3.0/drift-agent_linux_arm64.tar.gz"
      sha256 "7d9cd8190a25304820b04af20b54ea053dbab02be9ab5b9ef97824339edd5a3e"
      define_method(:install) do
        bin.install "drift-agent"
      end
    end
  end

  test do
    system "#{bin}/drift-agent", "--help"
  end
end
