# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftGuard < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftAgent/api-drift-engine"
  version "5.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_darwin_amd64.tar.gz"
      sha256 "6674e316fb78233e09686a60876becdca2118df64e787f4e3a37857a6b851aa6"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_darwin_arm64.tar.gz"
      sha256 "2c28c193e2d09a4a0bc5bba925e160135246e43d4fa808dd346ce520271c7888"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_linux_amd64.tar.gz"
      sha256 "82be4a17e08cf68734921b5b9027a2efa2ced459ebf55667f988d03090ca9484"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_linux_arm64.tar.gz"
      sha256 "47f2d2c61819ad289a85cdd11eccbd6db4ae98599a6d9d18087781ec2a1bc906"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  test do
    system "#{bin}/drift-guard", "--help"
  end
end
