# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftGuard < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftAgent/api-drift-engine"
  version "5.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_darwin_amd64.tar.gz"
      sha256 "f2de093998b5ceb4d4c3dd89759ba21f9f267a0ea700b3db83bce1ab8ebfc8a8"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_darwin_arm64.tar.gz"
      sha256 "431c41e13593cf94eb01d245b298f21c64e41855bbe9a6d752234f0525928aa8"

      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_linux_amd64.tar.gz"
      sha256 "19d07a5e7b202aa748ca2e0c029ccb2436f46e3ed844aaf455ea3b6de5c4bf5a"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.1.0/drift-guard_linux_arm64.tar.gz"
      sha256 "302fda65bcfc71a295d9f30a43b2d2c90da6e98a2b60e89c68f884b5ceb937d9"
      define_method(:install) do
        bin.install "drift-guard"
      end
    end
  end

  test do
    system "#{bin}/drift-guard", "--help"
  end
end
