# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DriftAgent < Formula
  desc "Schema diff engine that detects breaking vs. non-breaking API contract changes across OpenAPI, GraphQL, and gRPC schemas."
  homepage "https://github.com/DriftAgent/api-drift-engine"
  version "5.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.2.0/drift-agent_darwin_amd64.tar.gz"
      sha256 "688709ccef03a0704a0ec3a956608022fd4da29c8cf0333560a084451c67cc7a"

      define_method(:install) do
        bin.install "drift-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.2.0/drift-agent_darwin_arm64.tar.gz"
      sha256 "6ff6270dbe4eb9d9d650b67c260363e9aaad0d3fe7233fa337932235a5742ca6"

      define_method(:install) do
        bin.install "drift-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.2.0/drift-agent_linux_amd64.tar.gz"
      sha256 "003b6654b3aac790d221d7701deecfff1b6d5da57d1d6ec9c7a834ca6c533a34"
      define_method(:install) do
        bin.install "drift-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DriftAgent/api-drift-engine/releases/download/v5.2.0/drift-agent_linux_arm64.tar.gz"
      sha256 "457e0739900eac97f145257665676794d3eaa4be37953de721fe8f4047c67d7d"
      define_method(:install) do
        bin.install "drift-agent"
      end
    end
  end

  test do
    system "#{bin}/drift-agent", "--help"
  end
end
